//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEditor;
using EasyExcel;

namespace EasyExcelGenerated
{
	[CustomEditor(typeof(MainConfig_RedValueConfig_Sheet))]
	public class MainConfig_RedValueConfigInspector : EEAssetInspector
	{
	}
}
