//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEditor;
using EasyExcel;

namespace EasyExcelGenerated
{
	[CustomEditor(typeof(新增的表_炸弹飞现金_Sheet))]
	public class 新增的表_炸弹飞现金Inspector : EEAssetInspector
	{
	}
}
