//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class TaskGet : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _ID;
		public int ID { get { return _ID; } }

		[SerializeField]
		private int _GetM;
		public int GetM { get { return _GetM; } }


		public TaskGet()
		{
		}

#if UNITY_EDITOR
		public TaskGet(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _ID);
			TryParse(sheet[row][column++], out _GetM);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class Cat_TaskGet_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<TaskGet> elements = new List<TaskGet>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as TaskGet);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
