//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class Share : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _ID;
		public int ID { get { return _ID; } }

		[SerializeField]
		private string _gem;
		public string gem { get { return _gem; } }

		[SerializeField]
		private int _weight;
		public int weight { get { return _weight; } }


		public Share()
		{
		}

#if UNITY_EDITOR
		public Share(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _ID);
			TryParse(sheet[row][column++], out _gem);
			TryParse(sheet[row][column++], out _weight);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class GameValue_Share_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<Share> elements = new List<Share>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as Share);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
