//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class Guide : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _ID;
		public int ID { get { return _ID; } }

		[SerializeField]
		private string _SpriteName1;
		public string SpriteName1 { get { return _SpriteName1; } }

		[SerializeField]
		private string _SpriteName2;
		public string SpriteName2 { get { return _SpriteName2; } }

		[SerializeField]
		private string _Des1;
		public string Des1 { get { return _Des1; } }


		public Guide()
		{
		}

#if UNITY_EDITOR
		public Guide(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _ID);
			TryParse(sheet[row][column++], out _SpriteName1);
			TryParse(sheet[row][column++], out _SpriteName2);
			TryParse(sheet[row][column++], out _Des1);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class GuideData_Guide_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<Guide> elements = new List<Guide>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as Guide);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
