//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class EcpmConfig : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _ID;
		public int ID { get { return _ID; } }

		[SerializeField]
		private int _EcpmMin;
		public int EcpmMin { get { return _EcpmMin; } }

		[SerializeField]
		private int _EcpmMax;
		public int EcpmMax { get { return _EcpmMax; } }

		[SerializeField]
		private float _RewNum;
		public float RewNum { get { return _RewNum; } }

		[SerializeField]
		private float _NorNum;
		public float NorNum { get { return _NorNum; } }


		public EcpmConfig()
		{
		}

#if UNITY_EDITOR
		public EcpmConfig(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _ID);
			TryParse(sheet[row][column++], out _EcpmMin);
			TryParse(sheet[row][column++], out _EcpmMax);
			TryParse(sheet[row][column++], out _RewNum);
			TryParse(sheet[row][column++], out _NorNum);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class MainConfig_EcpmConfig_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<EcpmConfig> elements = new List<EcpmConfig>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as EcpmConfig);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
