//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class RandomName : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _ID;
		public int ID { get { return _ID; } }

		[SerializeField]
		private string _Name;
		public string Name { get { return _Name; } }

		[SerializeField]
		private int _Count;
		public int Count { get { return _Count; } }


		public RandomName()
		{
		}

#if UNITY_EDITOR
		public RandomName(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _ID);
			TryParse(sheet[row][column++], out _Name);
			TryParse(sheet[row][column++], out _Count);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class MainConfig_RandomName_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<RandomName> elements = new List<RandomName>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as RandomName);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
