//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class SignRedConfig : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _ID;
		public int ID { get { return _ID; } }

		[SerializeField]
		private int _AwardType;
		public int AwardType { get { return _AwardType; } }

		[SerializeField]
		private int _AwardCount;
		public int AwardCount { get { return _AwardCount; } }

		[SerializeField]
		private int _MostGet;
		public int MostGet { get { return _MostGet; } }


		public SignRedConfig()
		{
		}

#if UNITY_EDITOR
		public SignRedConfig(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _ID);
			TryParse(sheet[row][column++], out _AwardType);
			TryParse(sheet[row][column++], out _AwardCount);
			TryParse(sheet[row][column++], out _MostGet);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class MainConfig_SignRedConfig_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<SignRedConfig> elements = new List<SignRedConfig>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as SignRedConfig);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
