//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class LuckySection : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _id;
		public int id { get { return _id; } }

		[SerializeField]
		private int _redIcon;
		public int redIcon { get { return _redIcon; } }

		[SerializeField]
		private int _nearQuota;
		public int nearQuota { get { return _nearQuota; } }

		[SerializeField]
		private int _bigQuota;
		public int bigQuota { get { return _bigQuota; } }


		public LuckySection()
		{
		}

#if UNITY_EDITOR
		public LuckySection(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _id);
			TryParse(sheet[row][column++], out _redIcon);
			TryParse(sheet[row][column++], out _nearQuota);
			TryParse(sheet[row][column++], out _bigQuota);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class RedWithdrawConfig_LuckySection_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<LuckySection> elements = new List<LuckySection>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as LuckySection);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
