//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class DynamicRedConfig : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _id;
		public int id { get { return _id; } }

		[SerializeField]
		private float _value1;
		public float value1 { get { return _value1; } }

		[SerializeField]
		private float _value2;
		public float value2 { get { return _value2; } }

		[SerializeField]
		private float _dayWD;
		public float dayWD { get { return _dayWD; } }


		public DynamicRedConfig()
		{
		}

#if UNITY_EDITOR
		public DynamicRedConfig(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _id);
			TryParse(sheet[row][column++], out _value1);
			TryParse(sheet[row][column++], out _value2);
			TryParse(sheet[row][column++], out _dayWD);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class RedWithdrawConfig_DynamicRedConfig_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<DynamicRedConfig> elements = new List<DynamicRedConfig>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as DynamicRedConfig);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
