//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class WithdrawDamping : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _id;
		public int id { get { return _id; } }

		[SerializeField]
		private float _min;
		public float min { get { return _min; } }

		[SerializeField]
		private float _max;
		public float max { get { return _max; } }

		[SerializeField]
		private int _scale;
		public int scale { get { return _scale; } }


		public WithdrawDamping()
		{
		}

#if UNITY_EDITOR
		public WithdrawDamping(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _id);
			TryParse(sheet[row][column++], out _min);
			TryParse(sheet[row][column++], out _max);
			TryParse(sheet[row][column++], out _scale);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class RedWithdrawConfig_WithdrawDamping_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<WithdrawDamping> elements = new List<WithdrawDamping>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as WithdrawDamping);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
