//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class TwistedWDConfig : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _id;
		public int id { get { return _id; } }

		[SerializeField]
		private float _reward;
		public float reward { get { return _reward; } }

		[SerializeField]
		private string[] _keys;
		public string[] keys { get { return _keys; } }


		public TwistedWDConfig()
		{
		}

#if UNITY_EDITOR
		public TwistedWDConfig(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _id);
			TryParse(sheet[row][column++], out _reward);
			string[] _keysArray = sheet[row][column++].Split(',');
			int _keysCount = _keysArray.Length;
			_keys = new string[_keysCount];
			for(int i = 0; i < _keysCount; i++)
				TryParse(_keysArray[i], out _keys[i]);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class TwistedConfig_TwistedWDConfig_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<TwistedWDConfig> elements = new List<TwistedWDConfig>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as TwistedWDConfig);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
