//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class DebrisConfig : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _id;
		public int id { get { return _id; } }

		[SerializeField]
		private int _debris;
		public int debris { get { return _debris; } }

		[SerializeField]
		private int _reward;
		public int reward { get { return _reward; } }


		public DebrisConfig()
		{
		}

#if UNITY_EDITOR
		public DebrisConfig(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _id);
			TryParse(sheet[row][column++], out _debris);
			TryParse(sheet[row][column++], out _reward);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class TwistedConfig_DebrisConfig_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<DebrisConfig> elements = new List<DebrisConfig>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as DebrisConfig);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
