//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class TaskConfig : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _id;
		public int id { get { return _id; } }

		[SerializeField]
		private int _black1;
		public int black1 { get { return _black1; } }

		[SerializeField]
		private int _black2;
		public int black2 { get { return _black2; } }

		[SerializeField]
		private int _black3;
		public int black3 { get { return _black3; } }

		[SerializeField]
		private int _black4;
		public int black4 { get { return _black4; } }

		[SerializeField]
		private int _black5;
		public int black5 { get { return _black5; } }

		[SerializeField]
		private int _black6;
		public int black6 { get { return _black6; } }


		public TaskConfig()
		{
		}

#if UNITY_EDITOR
		public TaskConfig(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _id);
			TryParse(sheet[row][column++], out _black1);
			TryParse(sheet[row][column++], out _black2);
			TryParse(sheet[row][column++], out _black3);
			TryParse(sheet[row][column++], out _black4);
			TryParse(sheet[row][column++], out _black5);
			TryParse(sheet[row][column++], out _black6);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class TwistedConfig_TaskConfig_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<TaskConfig> elements = new List<TaskConfig>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as TaskConfig);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
